cookie:
  expiry_days: 0
  key: PawRescue
  name: none
credentials:
  usernames:
    ahmed bilal:
      email: crazy_bilal@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Ahmed Bilal
      password: $2b$12$WQJkpXrex6l3/uUF2zZgoeIRws/GcIwyM46mxyY8v./8RLTjBqk8e
    anam rafiq:
      email: anamrafiq@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Anam Rafiq
      password: $2b$12$uKLz8r8K/eh4XPk1vgajVOI7q/oWguhdPi.Tw40d2AJrTbU1yeVHS
    dr sajdeen:
      email: sajdeen@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Dr Sajdeen
      password: $2b$12$4Z.hgm9GYM79xC4UB8wfl.3hLEdtFgrNEPYofWtHdKO4t8JHSFv8.
    eman fatima:
      email: eman.fatima@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Eman Fatima
      password: $2b$12$HH9dSM0tGuxHG3ZPJGdi6OHTD/B3xhF3PkFaEb1HvgpdE2e1GFe66
    fakeha faisal:
      email: fakeha.faisal@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Fakeha Faisal
      password: $2b$12$8AtPJbMEwdhu3yB8/4le7ujk.A5lnK6kqh5G8RKI6uz15H0Yz7eIW
    hunain theba:
      email: hunain.theba@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Hunain Theba
      password: $2b$12$6LWaaRMP14MQPAuGRMIHluWCthMcqNzA63dYeQYgm2gdNhN1KkmHO
    ibad nadeem:
      email: in@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Ibad Nadeem
      password: nadeem12345
    maida butt:
      email: maida.aftab.butt@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Maida Butt
      password: $2b$12$v67mf5ISXQmoTNad7EaWc.hQEMDn77YJyTba8Dwy06LSxKRMpgcnW
    muhammad ibad:
      email: ibad.nadeem@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Muhammad Ibad
      password: $2b$12$14KalSr6PwrUCCMed.MfheeE7E1eYU7f9prO/Xh0zcck5OoMAR5a.
    syeda maryum:
      email: syeda.marry@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Syeda Maryum
      password: $2b$12$w1EOTb0YiRLh.1vjtlEmBe/Uci1NDJ0vl4Cm5eQaioS11JUTrAd52
pre-authorized:
  emails:
  - ibad29377@gmail.com
