USE [master]
GO
/****** Object:  Database [SchemaPawRescue]    Script Date: 9/14/2024 11:17:58 PM ******/
CREATE DATABASE [SchemaPawRescue]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SchemaPawRescue', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.FONTAINE\MSSQL\DATA\SchemaPawRescue.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SchemaPawRescue_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.FONTAINE\MSSQL\DATA\SchemaPawRescue_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SchemaPawRescue] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SchemaPawRescue].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SchemaPawRescue] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET ARITHABORT OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SchemaPawRescue] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SchemaPawRescue] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SchemaPawRescue] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SchemaPawRescue] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET RECOVERY FULL 
GO
ALTER DATABASE [SchemaPawRescue] SET  MULTI_USER 
GO
ALTER DATABASE [SchemaPawRescue] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SchemaPawRescue] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SchemaPawRescue] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SchemaPawRescue] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SchemaPawRescue] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SchemaPawRescue] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'SchemaPawRescue', N'ON'
GO
ALTER DATABASE [SchemaPawRescue] SET QUERY_STORE = ON
GO
ALTER DATABASE [SchemaPawRescue] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SchemaPawRescue]
GO
/****** Object:  Table [dbo].[Cage]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cage](
	[cageID] [int] NOT NULL,
	[wardID] [int] NULL,
	[cageStatusID] [int] NULL,
	[date] [date] NULL,
	[cageNo] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[cageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[cageStatus]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[cageStatus](
	[cageStatusID] [int] NOT NULL,
	[cageStatus] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[cageStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cats]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cats](
	[catID] [int] NOT NULL,
	[catName] [nvarchar](max) NULL,
	[age] [decimal](3, 2) NULL,
	[genderID] [int] NULL,
	[typeID] [int] NULL,
	[cageID] [int] NULL,
	[externalID] [int] NULL,
	[statusID] [int] NULL,
	[admittedOn] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[catID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CatStatus]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CatStatus](
	[StatusID] [int] NOT NULL,
	[statusType] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[StatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Donations]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Donations](
	[donationID] [int] NOT NULL,
	[donorID] [int] NULL,
	[modeID] [int] NULL,
	[amount] [int] NULL,
	[date] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[donationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Externals]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Externals](
	[externalID] [int] NOT NULL,
	[name] [nvarchar](max) NOT NULL,
	[contactNum] [nvarchar](max) NOT NULL,
	[address] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[externalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Gender]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Gender](
	[genderID] [int] NOT NULL,
	[gender] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[genderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[InternalRole]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[InternalRole](
	[internalRoleID] [int] NOT NULL,
	[roleDesc] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[internalRoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Mode]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Mode](
	[modeID] [int] NOT NULL,
	[mode] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[modeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Revenue]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Revenue](
	[revenueID] [int] NOT NULL,
	[buyerID] [int] NULL,
	[modeID] [int] NULL,
	[date] [date] NULL,
	[amount] [int] NULL,
	[remarks] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[revenueID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transactions]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transactions](
	[transactionID] [int] NOT NULL,
	[modeID] [int] NULL,
	[amount] [int] NULL,
	[billFor] [nvarchar](max) NULL,
	[date] [date] NULL,
	[remarks] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[transactionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Treatment]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Treatment](
	[treatmentID] [int] NOT NULL,
	[catID] [int] NULL,
	[userID] [int] NULL,
	[dateTime] [datetime] NULL,
	[temperature] [nvarchar](max) NULL,
	[treatment] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[treatmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Type]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Type](
	[typeID] [int] NOT NULL,
	[type] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[typeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[userID] [int] NOT NULL,
	[userName] [nvarchar](max) NULL,
	[email] [nvarchar](max) NULL,
	[password] [nvarchar](max) NULL,
	[picture] [varbinary](max) NULL,
	[internalRoleID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[userID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ward]    Script Date: 9/14/2024 11:17:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ward](
	[wardID] [int] NOT NULL,
	[name] [nvarchar](max) NULL,
	[code] [nvarchar](max) NULL,
	[capacityCages] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[wardID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[cageStatus] ([cageStatusID], [cageStatus]) VALUES (1, N'Occupied')
GO
INSERT [dbo].[cageStatus] ([cageStatusID], [cageStatus]) VALUES (2, N'Free')
GO
INSERT [dbo].[cageStatus] ([cageStatusID], [cageStatus]) VALUES (3, N'Transferred')
GO
INSERT [dbo].[CatStatus] ([StatusID], [statusType]) VALUES (1, N'Expired')
GO
INSERT [dbo].[CatStatus] ([StatusID], [statusType]) VALUES (2, N'Move to healthy area')
GO
INSERT [dbo].[CatStatus] ([StatusID], [statusType]) VALUES (3, N'Adopted')
GO
INSERT [dbo].[CatStatus] ([StatusID], [statusType]) VALUES (4, N'Discharged')
GO
INSERT [dbo].[CatStatus] ([StatusID], [statusType]) VALUES (5, N'Under Treatment')
GO
INSERT [dbo].[CatStatus] ([StatusID], [statusType]) VALUES (6, N'Ready to discharge')
GO
INSERT [dbo].[CatStatus] ([StatusID], [statusType]) VALUES (7, N'Fostered')
GO
INSERT [dbo].[CatStatus] ([StatusID], [statusType]) VALUES (8, N'Healthy in lower portion')
GO
INSERT [dbo].[CatStatus] ([StatusID], [statusType]) VALUES (9, N'Under observation')
GO
INSERT [dbo].[CatStatus] ([StatusID], [statusType]) VALUES (10, N'Missing')
GO
INSERT [dbo].[CatStatus] ([StatusID], [statusType]) VALUES (11, N'Ready to move H.A')
GO
INSERT [dbo].[Gender] ([genderID], [gender]) VALUES (1, N'Male')
GO
INSERT [dbo].[Gender] ([genderID], [gender]) VALUES (2, N'Female')
GO
INSERT [dbo].[InternalRole] ([internalRoleID], [roleDesc]) VALUES (1, N'Administrator')
GO
INSERT [dbo].[InternalRole] ([internalRoleID], [roleDesc]) VALUES (2, N'Moderator')
GO
INSERT [dbo].[InternalRole] ([internalRoleID], [roleDesc]) VALUES (3, N'Surgeon')
GO
INSERT [dbo].[Mode] ([modeID], [mode]) VALUES (1, N'Online')
GO
INSERT [dbo].[Mode] ([modeID], [mode]) VALUES (2, N'Cash')
GO
INSERT [dbo].[Type] ([typeID], [type]) VALUES (1, N'Pet')
GO
INSERT [dbo].[Type] ([typeID], [type]) VALUES (2, N'Rescued')
GO
INSERT [dbo].[Type] ([typeID], [type]) VALUES (3, N'Stray')
GO
INSERT [dbo].[Users] ([userID], [userName], [email], [password], [picture], [internalRoleID]) VALUES (1, N'Ahmed Bilal', N'crazy_bilal@gmail.com', N'bilal', NULL, 1)
GO
/****** Object:  Index [UQ__Cage__883BC1077E0CE377]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[Cage] ADD UNIQUE NONCLUSTERED 
(
	[cageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__cageStat__6ED6D2D4B00263BE]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[cageStatus] ADD UNIQUE NONCLUSTERED 
(
	[cageStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__Cats__17B6DD278488DF2B]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[Cats] ADD UNIQUE NONCLUSTERED 
(
	[catID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__CatStatu__C8EE2042BB104CCB]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[CatStatus] ADD UNIQUE NONCLUSTERED 
(
	[StatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__Donation__F7F4F4321B789602]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[Donations] ADD UNIQUE NONCLUSTERED 
(
	[donationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__External__C796AB4EE19FB4A7]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[Externals] ADD UNIQUE NONCLUSTERED 
(
	[externalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__Gender__306E2221894311C8]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[Gender] ADD UNIQUE NONCLUSTERED 
(
	[genderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__Internal__3500FB48792108D2]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[InternalRole] ADD UNIQUE NONCLUSTERED 
(
	[internalRoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__Mode__68A26F7FAB43DFD5]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[Mode] ADD UNIQUE NONCLUSTERED 
(
	[modeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__Revenue__966DC6C75440472C]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[Revenue] ADD UNIQUE NONCLUSTERED 
(
	[revenueID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__Transact__9B57CF538C149859]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[Transactions] ADD UNIQUE NONCLUSTERED 
(
	[transactionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__Treatmen__D7AA5889C2D69A7F]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[Treatment] ADD UNIQUE NONCLUSTERED 
(
	[treatmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__Type__F04DF11BB9C344A9]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[Type] ADD UNIQUE NONCLUSTERED 
(
	[typeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__Users__CB9A1CDE92D8A596]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[Users] ADD UNIQUE NONCLUSTERED 
(
	[userID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__Ward__A14E2C71EF793168]    Script Date: 9/14/2024 11:17:58 PM ******/
ALTER TABLE [dbo].[Ward] ADD UNIQUE NONCLUSTERED 
(
	[wardID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Cage]  WITH CHECK ADD  CONSTRAINT [Cage_fk1] FOREIGN KEY([wardID])
REFERENCES [dbo].[Ward] ([wardID])
GO
ALTER TABLE [dbo].[Cage] CHECK CONSTRAINT [Cage_fk1]
GO
ALTER TABLE [dbo].[Cage]  WITH CHECK ADD  CONSTRAINT [Cage_fk2] FOREIGN KEY([cageStatusID])
REFERENCES [dbo].[cageStatus] ([cageStatusID])
GO
ALTER TABLE [dbo].[Cage] CHECK CONSTRAINT [Cage_fk2]
GO
ALTER TABLE [dbo].[Cats]  WITH CHECK ADD  CONSTRAINT [Cats_fk3] FOREIGN KEY([genderID])
REFERENCES [dbo].[Gender] ([genderID])
GO
ALTER TABLE [dbo].[Cats] CHECK CONSTRAINT [Cats_fk3]
GO
ALTER TABLE [dbo].[Cats]  WITH CHECK ADD  CONSTRAINT [Cats_fk4] FOREIGN KEY([typeID])
REFERENCES [dbo].[Type] ([typeID])
GO
ALTER TABLE [dbo].[Cats] CHECK CONSTRAINT [Cats_fk4]
GO
ALTER TABLE [dbo].[Cats]  WITH CHECK ADD  CONSTRAINT [Cats_fk5] FOREIGN KEY([cageID])
REFERENCES [dbo].[Cage] ([cageID])
GO
ALTER TABLE [dbo].[Cats] CHECK CONSTRAINT [Cats_fk5]
GO
ALTER TABLE [dbo].[Cats]  WITH CHECK ADD  CONSTRAINT [Cats_fk6] FOREIGN KEY([externalID])
REFERENCES [dbo].[Externals] ([externalID])
GO
ALTER TABLE [dbo].[Cats] CHECK CONSTRAINT [Cats_fk6]
GO
ALTER TABLE [dbo].[Cats]  WITH CHECK ADD  CONSTRAINT [Cats_fk7] FOREIGN KEY([statusID])
REFERENCES [dbo].[CatStatus] ([StatusID])
GO
ALTER TABLE [dbo].[Cats] CHECK CONSTRAINT [Cats_fk7]
GO
ALTER TABLE [dbo].[Donations]  WITH CHECK ADD  CONSTRAINT [Donations_fk1] FOREIGN KEY([donorID])
REFERENCES [dbo].[Externals] ([externalID])
GO
ALTER TABLE [dbo].[Donations] CHECK CONSTRAINT [Donations_fk1]
GO
ALTER TABLE [dbo].[Donations]  WITH CHECK ADD  CONSTRAINT [Donations_fk2] FOREIGN KEY([modeID])
REFERENCES [dbo].[Mode] ([modeID])
GO
ALTER TABLE [dbo].[Donations] CHECK CONSTRAINT [Donations_fk2]
GO
ALTER TABLE [dbo].[Revenue]  WITH CHECK ADD  CONSTRAINT [Revenue_fk1] FOREIGN KEY([buyerID])
REFERENCES [dbo].[Externals] ([externalID])
GO
ALTER TABLE [dbo].[Revenue] CHECK CONSTRAINT [Revenue_fk1]
GO
ALTER TABLE [dbo].[Revenue]  WITH CHECK ADD  CONSTRAINT [Revenue_fk2] FOREIGN KEY([modeID])
REFERENCES [dbo].[Mode] ([modeID])
GO
ALTER TABLE [dbo].[Revenue] CHECK CONSTRAINT [Revenue_fk2]
GO
ALTER TABLE [dbo].[Transactions]  WITH CHECK ADD  CONSTRAINT [Transactions_fk1] FOREIGN KEY([modeID])
REFERENCES [dbo].[Mode] ([modeID])
GO
ALTER TABLE [dbo].[Transactions] CHECK CONSTRAINT [Transactions_fk1]
GO
ALTER TABLE [dbo].[Treatment]  WITH CHECK ADD  CONSTRAINT [Treatment_fk1] FOREIGN KEY([catID])
REFERENCES [dbo].[Cats] ([catID])
GO
ALTER TABLE [dbo].[Treatment] CHECK CONSTRAINT [Treatment_fk1]
GO
ALTER TABLE [dbo].[Treatment]  WITH CHECK ADD  CONSTRAINT [Treatment_fk2] FOREIGN KEY([userID])
REFERENCES [dbo].[Users] ([userID])
GO
ALTER TABLE [dbo].[Treatment] CHECK CONSTRAINT [Treatment_fk2]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [Users_fk5] FOREIGN KEY([internalRoleID])
REFERENCES [dbo].[InternalRole] ([internalRoleID])
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [Users_fk5]
GO
USE [master]
GO
ALTER DATABASE [SchemaPawRescue] SET  READ_WRITE 
GO
